#! /bin/bash

### BEGIN INIT INFO
# Provides:		cattd
# Required-Start:	$all
# Required-Stop:	$local_fs $network $named
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Catt daemon
# Description:		Catt management service
### END INIT INFO

CATT_USER=root
NAME=catt_screen
DIR=/home/cat/src
DESC="Catt management service"

case "$1" in
start)
	if [[ `su $CATT_USER -c "screen -ls |grep $NAME"` ]]
		then
		echo "$DESC is already running"
	else
		echo "Starting $DESC in session $NAME"
		su $CATT_USER -c "cd $DIR; screen -dmS $NAME python catt.py"
	fi
	;;
stop)
	if [[ `su $CATT_USER -c "screen -ls |grep $NAME"` != "" ]]
		then
		echo -n "Stopping $DESC"
		su $CATT_USER -c "kill -2 $(ps h --ppid $(screen -ls | grep $NAME | cut -d. -f1) -o pid)"
		echo "...done."
	else
		echo "Couldn't find a running $DESC"
	fi
	;;
restart)
	if [[ `su $CATT_USER -c "screen -ls |grep $NAME"` ]]
		then
		echo -n "Stopping $DESC"
		su $CATT_USER -c "kill -2 $(ps h --ppid $(screen -ls | grep $NAME | cut -d. -f1) -o pid)"
		echo "...done."
	else
		echo "Couldn't find a running $DESC"
	fi
	echo "Starting $DESC in session $NAME"
	su $CATT_USER -c "cd $DIR; screen -dmS $NAME python catt.py"
	;;
status)
	if [[ `su $CATT_USER -c "screen -ls |grep $NAME"` ]]
		then		
		echo "$DESC is running"
	else
		echo "$DESC is not running"
	fi
	;;
 *)
 	echo "Usage: $0 {start|stop|status|restart}"
    	exit 1
    	;;
 esac


